env: dev
region: weu

image:
  repository: acrwebdevglobal.azurecr.io/web

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

agc:
  hostnames: []
  tls:
    enabled: false
    secretName: ""
